### ISSUE TITLE
Strings as post data

### ISSUE THREAD

**Issue by dexterpratt** [ndexbio/ndex-java-client#3]
in updateUserEmail and updateUserPassword, we need to post strings but the current setup is expecting json post data.  Whats the resolution. Does this affect the v1.0 release?

**Comment by jingjingbic** [comment]
Vlad, could you take a look of this?

**Comment by vrynkov** [comment]
A new method, 
    public boolean changePassword(String newPassword)
has been added to NdexRestClientModelAccessLayer class.  This method calls another newly-added method, 
public int postString(
			final String route, 
			final String postData,
			final Class<? extends NdexObject>  mappedClass)
defined in NdexRestClient class.  
Together, the above two new methods implement the password changing functionality by "posting the string".

Currently, we do not update user email, so no need to implement the updateUserEmail() method.
